name: Generate pacman animation

on:
  schedule: 
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: List files in the current directory for debugging
        run: ls -alh

      - name: Check if pacman-contribution-graph.svg exists
        run: |
          if [ ! -f pacman-contribution-graph.svg ]; then
            echo "Error: pacman-contribution-graph.svg not found!"
            exit 1
          fi

      - name: Move graph to dist directory
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
